apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
        tier: frontend
    spec:
      serviceAccountName: gcp-pr-ksa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image.repository}}{{.Values.image.repoImgVersion}}
          ports: 
            - containerPort: {{.Values.service.port}}
              protocol: TCP
      imagePullSecrets:
      - name: artifact-registry
