apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: default
  annotations:
    prometheus.io/port: {{.Values.metrics.port}}
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: {{.Values.name}}

spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.fwdPort}}
      protocol: TCP
      name: {{.Values.service.name}}
    - port: 9000
      targetPort: {{.Values.service.fwdPort}}
      name: {{.Values.metrics.port}}
      protocol: TCP
  selector:
    app: {{.Values.appName}}
    tier: frontend
