replicaCount: 1

name: gcp-pr-fe
appName: gcp-pr
beName: gcp-pr-be

image:
  repository: europe-west2-docker.pkg.dev/gcp-project-replica-391115/gcp-pr-container-reg-fe/gcp-pr-fe
  repoImgVersion: :1.28
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5173
  fwdPort: 80
  name: frontend-service
  bePort: 8080

metrics:
  port: metrics-fe

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80