replicaCount: 1

name: gcp-pr-be
appName: gcp-pr

image:
  repository: europe-west2-docker.pkg.dev/gcp-project-replica-391115/gcp-pr-container-reg-be/gcp-pr-be
  repoImgVersion: :1.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8050
  name: backend-service
  fwdPort: 8080 

metrics:
  port: metrics-be

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
