replicaCount: 1

name: gcp-pr-be
appName: gcp-pr
feName: gcp-pr-fe

image:
  repository: europe-west2-docker.pkg.dev/gcp-project-replica-391115/gcp-pr-container-reg-be/gcp-pr-be
  repoImgVersion: :latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  name: backend-service
  fwdPort: 8080 
  fePort: 5173

metrics:
  port: metrics-be

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
