apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
      tier: backend
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
        tier: backend
    spec:
      containers:
        - name: {{.Values.appName}}
          image: {{.Values.image.repository}}{{.Values.image.repoImgVersion}}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{.Values.service.port}}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: {{.Values.service.port}}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports: 
            - containerPort: {{.Values.service.port}}
              protocol: TCP
      imagePullSecrets:
      - name: artifact-registry
