apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gcp-pr-be-service-monitor
  namespace: default
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: {{.Values.metrics.port}}
      scheme: http
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{.Values.appName}}
